version: '3'

services:
  localstack:
    build:
      context: ./images/localstack
      dockerfile: Dockerfile
    environment:
      SERVICES: dynamodb, lambda
      DATA_DIR: /var/lib/localstack/data
      DEFAULT_REGION: ap-northeast-1
      DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - 4566:4566
    volumes:
      - ./init_services:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/var/lib/localstack/data
volumes:
  localstack-data:
